name: qsblue-niri-dms
image-version: 43
base-image: ghcr.io/ublue-os/sway-base
modules:
  - type: dnf
    repos:
      copr:
        - avengemedia/dms
        - avengemedia/danklinux
        - ublue-os/packages
  - type: rpm-ostree        
    install:
      - niri
      - alacritty
      - xwayland-satellite
      - greetd
      - greetd-tuigreet
      - greetd-selinux
      - qt6-qtwayland
      - xdg-desktop-portal-gnome
      - wl-clipboard
      - network-manager-applet
      - quickshell
      - matugen
      - material-symbols-fonts
      - dms
      - dms-greeter
      - wlsunset
      - cliphist
      - imv
      - mpv
      - nemo
      - mousepad
      - hyprpolkitagent
    remove:
      - firefox
      - firefox-langpacks
      - sddm

  - type: files
    files:
      - source: system_files
        destination: /

  - type: systemd
    system:
      enabled:
        - greetd
        - firewalld
        - cliphist

description: "QuickBlue - Niri + DankMaterialShell + DMS Greeter + Brave dev setup"
